/*
 * Copyright (C) 1999-2009, Edmundo Albuquerque de Souza e Silva.
 *
 * This file may be distributed under the terms of the Q Public License
 * as defined by Trolltech AS of Norway and appearing in the file
 * LICENSE.QPL included in the packaging of this file.
 *
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTY OF ANY KIND, INCLUDING
 * THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,
 * INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
 * FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

package Tangram2;

public class T2Analytical_Stationary_Exact extends javax.swing.JPanel {

  /** Initializes the Form */

  public T2Analytical_Stationary_Exact(T2modelenv ModelEnv) {
    modelenv = ModelEnv;
    initComponents ();
    initComponentsManual ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
private void initComponents () {//GEN-BEGIN:initComponents
    jP_Exact_Methods = new javax.swing.JPanel ();
    jTB_GTH_block = new javax.swing.JToggleButton ();
    jTB_GTH_no_block = new javax.swing.JToggleButton ();
    jL_GTH_block = new javax.swing.JLabel ();
    jL_GTH_no_block = new javax.swing.JLabel ();
    setLayout (new org.netbeans.lib.awtextra.AbsoluteLayout ());

    jP_Exact_Methods.setLayout (new org.netbeans.lib.awtextra.AbsoluteLayout ());
    jP_Exact_Methods.setBorder (new javax.swing.border.LineBorder(java.awt.Color.gray));

      jTB_GTH_block.addChangeListener (new javax.swing.event.ChangeListener () {
          public void stateChanged (javax.swing.event.ChangeEvent evt) {
              jTB_GTH_blockStateChanged (evt);
          }
      }
      );
  
      jP_Exact_Methods.add (jTB_GTH_block, new org.netbeans.lib.awtextra.AbsoluteConstraints (11, 20, 15, 15));
  
      jTB_GTH_no_block.setSelected (true);
  
      jP_Exact_Methods.add (jTB_GTH_no_block, new org.netbeans.lib.awtextra.AbsoluteConstraints (11, 260, 15, 15));
  
      jL_GTH_block.setText ("GTH block elimination");
      jL_GTH_block.setForeground (java.awt.Color.black);
      jL_GTH_block.setFont (new java.awt.Font ("Dialog", 1, 10));
  
      jP_Exact_Methods.add (jL_GTH_block, new org.netbeans.lib.awtextra.AbsoluteConstraints (30, 20, -1, 17));
  
      jL_GTH_no_block.setText ("GTH no block");
      jL_GTH_no_block.setForeground (java.awt.Color.black);
      jL_GTH_no_block.setFont (new java.awt.Font ("Dialog", 1, 10));
  
      jP_Exact_Methods.add (jL_GTH_no_block, new org.netbeans.lib.awtextra.AbsoluteConstraints (30, 260, -1, 17));
  

    add (jP_Exact_Methods, new org.netbeans.lib.awtextra.AbsoluteConstraints (10, 10, 550, 330));

}//GEN-END:initComponents

  private void jTB_GTH_blockStateChanged (javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTB_GTH_blockStateChanged
    //GTH block elimination radio button
    boolean state = jTB_GTH_block.isSelected();

    Mat_Manager.setEnabledComponents(state);
  }//GEN-LAST:event_jTB_GTH_blockStateChanged


  private void initComponentsManual()
  {
    javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
    group.add(jTB_GTH_block);
    group.add(jTB_GTH_no_block);

    Mat_Manager = new T2Matrix_Blocks_Manager (modelenv.curdir,modelenv.curmodel);
    jP_Exact_Methods.add(Mat_Manager, new org.netbeans.lib.awtextra.AbsoluteConstraints (60, 40, -1, -1));
    Mat_Manager.setEnabledComponents(false);
  }

  public void Evaluate()
  {
    String command;

   //GTH block elimination was selected
    if (jTB_GTH_block.isSelected()) {

        if (!Mat_Manager.validateBlocks())
          return;

        command = "solv " + modelenv.curmodel + " 6";
    }
    else {//GTH no block was selected
        command = "solv " + modelenv.curmodel + " 5";
    }

    modelenv.analytical.setEnabled(false);
    status = new T2status(modelenv.analytical, "Solver Status", "Solv is running", command, 0 ,(modelenv.outputdevice ? modelenv.fileout : modelenv.outputscreen), (modelenv.outputdevice ? modelenv.fileout : modelenv.outputscreen));
    status.show();
    status.start();
  }

  public String Get_Method_Name() {
    return "Exact";
  }

  public void KillChild()
  {
    if( status != null )
    {
      status.Proc.destroy();
      status.dispose();
    }
  }


// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JPanel jP_Exact_Methods;
private javax.swing.JToggleButton jTB_GTH_block;
private javax.swing.JToggleButton jTB_GTH_no_block;
private javax.swing.JLabel jL_GTH_block;
private javax.swing.JLabel jL_GTH_no_block;
// End of variables declaration//GEN-END:variables
  private T2modelenv modelenv;
  private T2status status;
  private T2Matrix_Blocks_Manager Mat_Manager;

}
