/*
 * Copyright (C) 1999-2009, Edmundo Albuquerque de Souza e Silva.
 *
 * This file may be distributed under the terms of the Q Public License
 * as defined by Trolltech AS of Norway and appearing in the file
 * LICENSE.QPL included in the packaging of this file.
 *
 * THIS FILE IS PROVIDED AS IS WITH NO WARRANTY OF ANY KIND, INCLUDING
 * THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,
 * INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
 * FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

package Tangram2;

public class T2Analytical_Iterative_Methods extends javax.swing.JPanel {

  /** Initializes the Form */
  public T2Analytical_Iterative_Methods() {
    initComponents ();
    initComponentsManual ();
  }


  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTB_Power = new javax.swing.JToggleButton();
        jL_Power = new javax.swing.JLabel();
        jTB_Gauss_Siedel = new javax.swing.JToggleButton();
        jL_Gauss_Siedel = new javax.swing.JLabel();
        jTB_Jacobi = new javax.swing.JToggleButton();
        jL_Jacobi = new javax.swing.JLabel();
        jL_SOR = new javax.swing.JLabel();
        jTB_SOR = new javax.swing.JToggleButton();
        jL_Iterative_Precision = new javax.swing.JLabel();
        jTF_Iterative_Precision = new javax.swing.JTextField();
        jTF_Max_Iterations = new javax.swing.JTextField();
        jL_Max_Iterations = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTB_Power.setSelected(true);
        add(jTB_Power, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 15, 15));

        jL_Power.setText("Power");
        jL_Power.setForeground(java.awt.Color.black);
        jL_Power.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_Power, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 17));

        add(jTB_Gauss_Siedel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 15, 15));

        jL_Gauss_Siedel.setText("Gauss-Siedel");
        jL_Gauss_Siedel.setForeground(java.awt.Color.black);
        jL_Gauss_Siedel.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_Gauss_Siedel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 17));

        add(jTB_Jacobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 15, 15));

        jL_Jacobi.setText("Jacobi");
        jL_Jacobi.setForeground(java.awt.Color.black);
        jL_Jacobi.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_Jacobi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 17));

        jL_SOR.setText("SOR");
        jL_SOR.setForeground(java.awt.Color.black);
        jL_SOR.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_SOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 17));

        add(jTB_SOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 15, 15));

        jL_Iterative_Precision.setText("Precision");
        jL_Iterative_Precision.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_Iterative_Precision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 20));

        jTF_Iterative_Precision.setToolTipText("Error bound");
        add(jTF_Iterative_Precision, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 100, 20));

        jTF_Max_Iterations.setToolTipText("Abort execution when this number is reached.");
        jTF_Max_Iterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Max_IterationsActionPerformed(evt);
            }
        });

        add(jTF_Max_Iterations, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, 20));

        jL_Max_Iterations.setText("Max number of iterations");
        jL_Max_Iterations.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jL_Max_Iterations, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 20));

        jLabel1.setText("Solution Method");
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    }//GEN-END:initComponents

  private void jTF_Max_IterationsActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Max_IterationsActionPerformed
    // Add your handling code here:
  }//GEN-LAST:event_jTF_Max_IterationsActionPerformed

  private void initComponentsManual()
  {
    javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
    group.add(jTB_Power);
    group.add(jTB_Gauss_Siedel);
    group.add(jTB_Jacobi);
    group.add(jTB_SOR);
  }

  public String Get_Precision()
  {
    return jTF_Iterative_Precision.getText();
  }

  public String Get_Max_Number_Of_Iterations()
  {
    return jTF_Max_Iterations.getText();
  }

  public int GetSelectedIterativeMethod()
  {
    if (jTB_Power.isSelected())
      return 1;
    if (jTB_Gauss_Siedel.isSelected())
      return 2;
    if (jTB_Jacobi.isSelected())
      return 3;
    if (jTB_SOR.isSelected())
      return 4;
    return -1;
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTF_Max_Iterations;
    private javax.swing.JLabel jL_SOR;
    private javax.swing.JToggleButton jTB_Jacobi;
    private javax.swing.JLabel jL_Jacobi;
    private javax.swing.JToggleButton jTB_SOR;
    private javax.swing.JLabel jL_Power;
    private javax.swing.JLabel jL_Iterative_Precision;
    private javax.swing.JToggleButton jTB_Gauss_Siedel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jL_Max_Iterations;
    private javax.swing.JLabel jL_Gauss_Siedel;
    private javax.swing.JToggleButton jTB_Power;
    private javax.swing.JTextField jTF_Iterative_Precision;
    // End of variables declaration//GEN-END:variables
  private T2modelenv modelenv;
  private T2status status;
}
