/*
 * To change this template, choose Tools \| Templates
 * and open the template in the editor.
 */

/*
 * T2hmm.java
 *
 * Created on 09/03/2009, 13:29:17
 */

/**
 *
 * @author Bruno
 */

package Tangram2;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

public class T2MTKHmmMethods extends javax.swing.JFrame {

    /** Creates new form T2hmm */
    public T2MTKHmmMethods() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tangram II");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Observation Source");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Viterbi", jPanel2);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Observation Source");

        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Likelihood", jPanel3);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        jLabel3.setText("Observation Source");

        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Window Size:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Forecast", jPanel4);

        jPanel6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel6ComponentShown(evt);
            }
        });

        jLabel6.setText("Number of Steps");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(388, 388, 388))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulate", jPanel6);

        jPanel8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel8ComponentShown(evt);
            }
        });

        jButton8.setText("Browse");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setText("Observation Source");

        jCheckBox2.setText("Steady State");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addGap(24, 24, 24))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 536, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("State Probability", jPanel8);

        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "From Observations", "From States" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("From States"));
        jPanel9.setEnabled(false);
        jPanel9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel9PropertyChange(evt);
            }
        });

        jLabel9.setText("Obsservation Source");
        jLabel9.setEnabled(false);

        jTextField6.setAutoscrolls(false);
        jTextField6.setEnabled(false);

        jButton9.setText("Browse");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel12.setText("States Path");
        jLabel12.setEnabled(false);

        jTextField8.setAutoscrolls(false);
        jTextField8.setEnabled(false);

        jButton12.setText("Browse");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12)
                            .addComponent(jButton9)))
                    .addComponent(jLabel12))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addGap(75, 75, 75))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("From Observations"));

        jTextField7.setText("0.001");
        jTextField7.setEnabled(false);

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel11.setText("Source Objects");

        jScrollPane1.setViewportView(jList1);

        jButton11.setText("Remove");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel10.setText("Iterations");

        jCheckBox1.setText("Log Likelihood Threshold");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel11)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Training", jPanel5);

        jPanel7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel7ComponentShown(evt);
            }
        });

        jLabel5.setText("Observation Source");

        jLabel7.setText("Future Steps");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE)
                .addGap(188, 188, 188))
        );

        jTabbedPane1.addTab("Symbol Value Sum Distribution", jPanel7);

        jPanel18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel18ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Symbol Value Time Average", jPanel18);

        jLabel14.setText(T2MTKCommon.statusBarUpdate());
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setText("View Matrix");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Results");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tangram2/imgs/tang_measures.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

       resForm = new T2MTKHmmResults(this.results);
       resForm.setVisible(true);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //new T2MTKHmmView().setVisible(true);
        (new T2MTKHmmMatrixperm()).show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField1.setText(file.getPath());
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField2.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField3.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
            int method = jTabbedPane1.getSelectedIndex();
            boolean hasResult = false;

            switch (method){
                case 0: hasResult = viterbi();
                        break;
                case 1: hasResult = likelihood();
                        break;
                case 2: hasResult = forecast();
                        break;
                case 3: hasResult = simulate();
                        break;
                case 4: hasResult = state_prob();
                        break;
                case 5: hasResult = train();
                        break;
                case 6: hasResult = symb_sum_dist();
                        break;
                case 7: hasResult = symb_tavg();
                        break;
            }

            if(hasResult)  {
                T2MTKCommon.infoMessage("", "Method has successfully finished. To view its results, click on the Results button.");
                jButton4.setEnabled(true);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField4.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField5.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField6.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedIndex()==0){

            //Observations
            File resFile= new File(currdir+currmodel+".HMM.training.output");
            if(resFile.exists()) jButton4.setEnabled(true);
            else jButton4.setEnabled(false);

            for(Component comp : jPanel9.getComponents()){
                comp.setEnabled(false);
            }
            jPanel9.setEnabled(false);
            for(Component comp : jPanel17.getComponents()){
                comp.setEnabled(true);
            }
            jList1.setEnabled(true);
            jPanel10.setEnabled(true);
        }
        if(jComboBox1.getSelectedIndex()==1){

            //States
            File resFile= new File(currdir+currmodel+".HMM.training_from_states.output");
            if(resFile.exists()) jButton4.setEnabled(true);
            else jButton4.setEnabled(false);

            for(Component comp : jPanel9.getComponents()){
                comp.setEnabled(true);
            }
            jPanel9.setEnabled(true);
            for(Component comp : jPanel17.getComponents()){
                comp.setEnabled(false);
            }
            jList1.setEnabled(false);
            jPanel17.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            lModel.addElement(file.getPath());
            jList1.setModel(lModel);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        lModel.removeElementAt(jList1.getSelectedIndex());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jTextField7.setEnabled(true);
        }else jTextField7.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.viterbi.output");
        if(resFile.exists()) {
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        } else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.likelihood.output");
        if(resFile.exists()) {
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.forecast.output");
        if(resFile.exists()){
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel4ComponentShown

    private void jPanel6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.simulate.output");
        if(resFile.exists()){
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel6ComponentShown

    private void jPanel7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel7ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.symb_sum_dist.output");
        if(resFile.exists()){
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel7ComponentShown

    private void jPanel8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel8ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.state_prob.output");
        if(resFile.exists()){
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel8ComponentShown

    private void jPanel9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel9PropertyChange

    }//GEN-LAST:event_jPanel9PropertyChange

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
        if(jComboBox1.getSelectedIndex()==0){
            //Observations
            File resFile= new File(currdir+currmodel+".HMM.training.output");
            if(resFile.exists()){
                jButton4.setEnabled(true);
                try {
                    BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                    results = "";
                    while(resBuf.ready()){
                        results += resBuf.readLine()+"\n";
                    }
                    resBuf.close();
                } catch (FileNotFoundException ex) {
                    T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
                }
            }
            else jButton4.setEnabled(false);
        }
        if(jComboBox1.getSelectedIndex()==1){
            //States
            File resFile= new File(currdir+currmodel+".HMM.training_from_states.output");
            if(resFile.exists()){
                jButton4.setEnabled(true);
                try {
                    BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                    results = "";
                    while(resBuf.ready()){
                        results += resBuf.readLine()+"\n";
                    }
                    resBuf.close();
                } catch (FileNotFoundException ex) {
                    T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
                }
            }
            else jButton4.setEnabled(false);
        }
    }//GEN-LAST:event_jPanel5ComponentShown

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setCurrentDirectory(new File(currdir+currmodel+".HMM.parameters"));
        int ret = fc.showOpenDialog(null);
        if (ret == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fc.getSelectedFile();
            jTextField8.setText(file.getPath());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jPanel18ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel18ComponentShown
        File resFile= new File(currdir+currmodel+".HMM.symb_tavg.output");
        if(resFile.exists()){
            jButton4.setEnabled(true);
            try {
                BufferedReader resBuf = new BufferedReader(new FileReader(resFile));
                results = "";
                while(resBuf.ready()){
                    results += resBuf.readLine()+"\n";
                }
                resBuf.close();
            } catch (FileNotFoundException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            } catch (IOException ex) {
                T2MTKCommon.errorMessage("", "Error reading results file: "+ex.getMessage());
            }
        }
        else jButton4.setEnabled(false);
    }//GEN-LAST:event_jPanel18ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        SpinnerModel sModel1 = new SpinnerNumberModel(1,1,999999,1);
        jSpinner1.setModel(sModel1);
        SpinnerModel sModel2 = new SpinnerNumberModel(1,1,999999,1);
        jSpinner2.setModel(sModel2);
        SpinnerModel sModel3 = new SpinnerNumberModel(1,1,999999,1);
        jSpinner3.setModel(sModel3);
        SpinnerModel sModel4 = new SpinnerNumberModel(1,1,999999,1);
        jSpinner4.setModel(sModel4);
        
    }//GEN-LAST:event_formComponentShown

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()){
            jButton8.setEnabled(false);
            jTextField5.setEnabled(false);
            jLabel8.setEnabled(false);
        }else{
            jButton8.setEnabled(true);
            jTextField5.setEnabled(true);
            jLabel8.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void createHmm(String obsFile){

        T2MTKCommon.createCmds();
        if(!obsFile.equals("")){
            T2MTKCommon.addCmd("i = new intvalue()");
            T2MTKCommon.addCmd("i.load(\""+obsFile+"\")");
        }
        T2MTKCommon.addCmd("store = new intvalue()");
        T2MTKCommon.addCmd("h = new hmm()");
        T2MTKCommon.addCmd("h.load(\""+currdir+"/"+currmodel+".HMM.parameters\")");

    }
    private boolean viterbi(){

        //OK 
        String obsFile = jTextField1.getText();
        if(obsFile.equals("")){
            T2MTKCommon.errorMessage("", "You must to select the observation source file.");
            return false;
        }
        createHmm(obsFile);
        T2MTKCommon.addCmd("h.viterbi(i,store)");
        T2MTKCommon.addCmd("store.save(\""+currdir+currmodel+".HMM.viterbi.hidden_states_path\")");
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.viterbi.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }

            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }
    private boolean likelihood(){

        //OK : passar estados ocultos?
        String obsFile = jTextField2.getText();
        if(obsFile.equals("")){
            T2MTKCommon.errorMessage("", "You must to select the observation source file.");
            return false;
        }
        createHmm(obsFile);
        T2MTKCommon.addCmd("h.likelihood(i)");
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.likelihood.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }
            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }

    private boolean forecast(){

        //OK 
        String obsFile = jTextField3.getText();
        if(obsFile.equals("")){
            T2MTKCommon.errorMessage("", "You must to select the observation source file.");
            return false;
        }
        createHmm(obsFile);
        T2MTKCommon.addCmd("h.forecast("+jSpinner1.getValue().toString()+",i,store)");
        T2MTKCommon.addCmd("store.save(\""+currdir+currmodel+".HMM.forecast.forecasted_values\")");
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.forecast.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }
            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }

    private boolean simulate(){

        //OK : Arquivos redundantes
        
        T2MTKCommon.clearCmds();
        T2MTKCommon.createCmds();
        T2MTKCommon.addCmd("Simul_Sample = new intvalue()");
        T2MTKCommon.addCmd("Hidden_States_Path = new intvalue()");
        T2MTKCommon.addCmd("h = new hmm()");
        T2MTKCommon.addCmd("h.load(\""+currdir+"/"+currmodel+".HMM.parameters\")");
        T2MTKCommon.addCmd("h.simulate("+jSpinner2.getValue().toString()+",Simul_Sample,Hidden_States_Path)");
        T2MTKCommon.addCmd("Simul_Sample.display(sample)");
        T2MTKCommon.addCmd("Simul_Sample.save(\""+currdir+"/"+currmodel+".HMM.simulate.simul_sample\")");
        T2MTKCommon.addCmd("Hidden_States_Path.display(sample)");
        T2MTKCommon.addCmd("Hidden_States_Path.save(\""+currdir+"/"+currmodel+".HMM.simulate.hidden_states_path\")");
        T2MTKMessages out  = T2MTKCommon.exec();

        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.simulate.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }
            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;

    }

    private boolean symb_tavg(){

        
        String obsFile = ""; //jTextField4.getText();
        createHmm(obsFile);
        T2MTKCommon.addCmd("h.symb_tavg()");
        
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.symb_tavg.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }

            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }

    private boolean symb_sum_dist(){


        String obsFile = jTextField4.getText();
        createHmm(obsFile);
        T2MTKCommon.addCmd("h.symb_sum_dist(i,"+jSpinner3.getValue()+")");
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.symb_sum_dist.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }

            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }

    private boolean state_prob(){

        //OK

        String obsFile = jTextField5.getText();
        createHmm(obsFile);
        if(jCheckBox2.isSelected()) T2MTKCommon.addCmd("h.state_prob()");
        else{
            if(obsFile.equals("")){
                T2MTKCommon.errorMessage("", "You must specify a observation source file.");
                return false;
            }else T2MTKCommon.addCmd("h.state_prob(i)");
        }
        T2MTKMessages out  = T2MTKCommon.exec();
        if(out.getError().equals("")){
            results = out.getOut();
            if(!out.getOut().equals("")){
                File output = new File(currdir+currmodel+".HMM.state_prob.output");
                if(output.exists()) output.delete();
                try {
                    PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                    outFile.println(out.getOut());
                    outFile.close();
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create results file.");
                }
            }

            return true;
        }else{
            T2MTKCommon.errorMessage("", out.getError());
        }
        return false;
    }
    private boolean train(){

        T2MTKMessages out = new T2MTKMessages();
        if(jComboBox1.getSelectedIndex()==0){
            // From Observations

            String params = jSpinner4.getValue().toString()+",";
            if(jTextField7.isEnabled()) params += jTextField7.getText()+",";
            T2MTKCommon.clearCmds();
            T2MTKCommon.createCmds();
            T2MTKCommon.addCmd("h = new hmm()");
            T2MTKCommon.addCmd("h.load(\""+currdir+"/"+currmodel+".HMM.parameters\")");
            for(int i=0;i<lModel.getSize();i++){
                
                T2MTKCommon.addCmd("obs"+i+" = new intvalue()");
                T2MTKCommon.addCmd("obs"+i+".load(\""+lModel.elementAt(i).toString()+"\")");
                params += "obs"+i+",";

            }
            params = params.substring(0, params.length()-1);
            T2MTKCommon.addCmd("h.training("+params+")");
            T2MTKCommon.addCmd("h.save(\""+currdir+currmodel+".HMM.parameters\")");
            //T2MTKCommon.addCmd("h.display(all)");
            out  = T2MTKCommon.exec();

            // Writing output file
            if(out.getError().equals("")){
                results = out.getOut();
                if(!out.getOut().equals("")){
                    File output = new File(currdir+currmodel+".HMM.training.output");
                    if(output.exists()) output.delete();
                    try {
                        PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                        //outFile.println(out.getOut().substring(0,out.getOut().indexOf("'all'")));
                        outFile.println(out.getOut());
                        outFile.close();
                    } catch (IOException ex) {
                        T2MTKCommon.errorMessage("", "Cannot create results file.");
                    }
                }
                // Updating view matrix files
                File hiddenStFile = new File(currdir + currmodel + ".HMM.hidden_st.st_trans_prob_mtx");
                File symbolsFile = new File(currdir + currmodel + ".HMM.symbols.st_trans_prob_mtx");
                if(hiddenStFile.exists()) hiddenStFile.delete();
                if(symbolsFile.exists()) symbolsFile.delete();
                PrintWriter hiddenStWriter = null;
                try {
                    hiddenStWriter = new PrintWriter(new FileWriter(hiddenStFile), true);
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create file: "+currmodel+".HMM.hidden_st.st_trans_prob_mtx. "+ex.getMessage());
                }
                PrintWriter symbolsWriter = null;
                try {
                    symbolsWriter = new PrintWriter(new FileWriter(symbolsFile), true);
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create file: "+currmodel+".HMM.symbols.st_trans_prob_mtx. "+ex.getMessage());
                }

                T2MTKHmm hmm = T2MTKHmmIO.hmmRead(currdir+currmodel+".HMM.parameters");

                double value;

                for(int i=0;i<hmm.getHstates();i++){
                    for(int j=0;j<hmm.getHstates();j++){
                        value = hmm.getHiddenStatesTransProb(i, j);
                        if(value > 0){
                            hiddenStWriter.println((i+1)+" "+(j+1)+" "+value);
                        }
                    }
                }
                for(int i=0;i<hmm.getHstates();i++){
                    for(int j=0;j<hmm.getSymbols();j++){
                        value = hmm.getSymbolGenProb(i, j);
                        if(value > 0){
                            symbolsWriter.println((i+1)+" "+(j+1)+" "+value);
                        }
                    }
                }
                hiddenStWriter.close();
                symbolsWriter.close();

                return true;
            }else{
                T2MTKCommon.errorMessage("", out.getError());
            }

            
            //List list = jList1.get

        }
        if(jComboBox1.getSelectedIndex()==1){
            // From States
            String obsFile = jTextField6.getText();
            String statesFile = jTextField8.getText();
            createHmm(obsFile);
            T2MTKCommon.addCmd("j = new intvalue()");
            T2MTKCommon.addCmd("j.load(\""+statesFile+"\")");
            T2MTKCommon.addCmd("h.training(i,j)");
            T2MTKCommon.addCmd("h.save(\""+currdir+currmodel+".HMM.parameters\")");
            T2MTKCommon.addCmd("h.display(all)");
            out  = T2MTKCommon.exec();
            if(out.getError().equals("")){
                results = out.getOut();

                /*if(!out.getOut().equals("")){
                    File output = new File(currdir+currmodel+".hmm.trained_from_states");
                    if(output.exists()) output.delete();
                    try {
                        PrintWriter outFile = new PrintWriter(new FileWriter(output), true);
                        outFile.println(out.getOut());
                        outFile.close();
                    } catch (IOException ex) {
                        T2MTKCommon.errorMessage("", "Cannot create results file.");
                    }
                }*/

                // Updating view matrix files
                File hiddenStFile = new File(currdir + currmodel + ".HMM.hidden_st.st_trans_prob_mtx");
                File symbolsFile = new File(currdir + currmodel + ".HMM.symbols.st_trans_prob_mtx");
                if(hiddenStFile.exists()) hiddenStFile.delete();
                if(symbolsFile.exists()) symbolsFile.delete();
                PrintWriter hiddenStWriter = null;
                try {
                    hiddenStWriter = new PrintWriter(new FileWriter(hiddenStFile), true);
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create file: "+currmodel+".HMM.hidden_st.st_trans_prob_mtx. "+ex.getMessage());
                }
                PrintWriter symbolsWriter = null;
                try {
                    symbolsWriter = new PrintWriter(new FileWriter(symbolsFile), true);
                } catch (IOException ex) {
                    T2MTKCommon.errorMessage("", "Cannot create file: "+currmodel+".HMM.symbols.st_trans_prob_mtx. "+ex.getMessage());
                }

                T2MTKHmm hmm = T2MTKHmmIO.hmmRead(currdir+currmodel+".HMM.parameters");

                double value;

                for(int i=0;i<hmm.getHstates();i++){
                    for(int j=0;j<hmm.getHstates();j++){
                        value = hmm.getHiddenStatesTransProb(i, j);
                        if(value > 0){
                            hiddenStWriter.println((i+1)+" "+(j+1)+" "+value);
                        }
                    }
                }
                for(int i=0;i<hmm.getHstates();i++){
                    for(int j=0;j<hmm.getSymbols();j++){
                        value = hmm.getSymbolGenProb(i, j);
                        if(value > 0){
                            symbolsWriter.println((i+1)+" "+(j+1)+" "+value);
                        }
                    }
                }
                hiddenStWriter.close();
                symbolsWriter.close();
                return true;
            }else{
                T2MTKCommon.errorMessage("", out.getError());
            }
        }
        

        return false;
    }


    public String getResults() {
        return results;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T2MTKHmmMethods().setVisible(true);
            }
        });
    }

    private String currdir = T2MTKCommon.currdir;
    private String currmodel = T2MTKCommon.currmodel;
    private String results = "";
    private T2MTKHmmResults resForm;
    private DefaultListModel lModel = new DefaultListModel();



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
