/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * T2hmmViewHMM.java
 *
 * Created on 09/03/2009, 13:48:24
 */

/**
 *
 * @author Bruno
 */
 
package Tangram2;

public class T2MTKHmmView extends javax.swing.JFrame {

    /** Creates new form T2hmmViewHMM */
    public T2MTKHmmView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tangram II - HMM View");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Hidden Markov Model");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        T2MTKHmm hmm = T2MTKHmmIO.hmmRead(hmmFile);

        if(hmm != null){
            int i,j;
            String buf = "";

            jTextArea1.setText("");
            jTextArea1.append("Number of Hidden States: "+hmm.getHstates()+"\n");
            jTextArea1.append("Number of Symbols: "+hmm.getSymbols()+"\n\n");

            for(i=0;i<hmm.getHstates();i++){
                buf += hmm.getInitStatesProb(i)+", ";
            }
            buf = buf.substring(0, buf.length()-2);

            jTextArea1.append("Initial probabilities of Hidden States: [ "+buf+"]\n\n");

            jTextArea1.append("Under construction...");

            /*for(i=0;i<hmm.getHstates();i++){
                buf = i+" ";
                for(j=0;j<hmm.getHstates();j++){
                    buf += buf + ""
                }
            }*/

        }


    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T2MTKHmmView().setVisible(true);
            }
        });
    }

    private String hmmFile = T2MTKCommon.currdir + T2MTKCommon.currmodel + ".HMM.parameters";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
