/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * T2MTKMain.java
 *
 * Created on 13/03/2009, 19:03:47
 */

/**
 *
 * @author Bruno
 */

package Tangram2;

public class T2MTKMain extends javax.swing.JFrame {

    /** Creates new form T2MTKMain */
    public T2MTKMain(T2modelenv mainHolder) {
        T2MainWindow = mainHolder;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tangram II");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hidden Markov Model",
                                                                                "Hierarchical Gilbert Hidden Markov Model",
                                                                                "Hierarchical General Hidden Markov Model - Fixed Batch",
                                                                                "Hierarchical General Hidden Markov Model - Variable Batch", }));

        jLabel1.setText("Select your model type:");

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        if(jComboBox1.getSelectedIndex()==0){
            new T2MTKHmmImportFromTangram().setVisible(true);
            this.dispose();
        }
        if(jComboBox1.getSelectedIndex()==1){
            new T2MTKHierarchicalHmmImportFromTangram().setVisible(true);
            modelType = "ghmm";
            this.dispose();
        }
        if(jComboBox1.getSelectedIndex()==2){
            new T2MTKHierarchicalHmmImportFromTangram().setVisible(true);
            modelType = "hmm_batch";
            this.dispose();
        }
        if(jComboBox1.getSelectedIndex()==3){
            new T2MTKHierarchicalHmmImportFromTangram().setVisible(true);
            modelType = "hmm_batch_variable";
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new T2MTKMain(T2MainWindow).setVisible(true);
            }
        });
    }

    public static String modelType;
    public static T2modelenv T2MainWindow;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
